language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      script: cd main/source/linux && make
      env: OPJ_CI_ARCH=i386
      addons:
        apt:
          packages:
            - gcc-multilib
            - g++-multilib
            - libcurl4-openssl-dev

    - os: osx
      compiler: clang
      before_script:
      - export CC=clang
      - export CPLUS=clang++
      script: cd main/source/linux && make